name = "webdav-ui"
pages_build_output_dir = "dist"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "NOTES_DB"
database_name = "notes"
database_id = "0dcb94cd-c8b4-4dfa-8a32-4328ddae0aa3"
