name = "r2-webdav-x"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "bucket"
bucket_name = "true-bucket"

[[d1_databases]]
binding = "notes"
database_name = "notes"
database_id = "0dcb94cd-c8b4-4dfa-8a32-4328ddae0aa3"

[vars]
CORS_ORIGIN = "https://webdav-ui.127631.xyz"
JWT_TTL_SECONDS = "2592000"

[observability]
enabled = true
head_sampling_rate = 1
